<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEbUMqQ8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEbUMqQ8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEbUMqQ8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEbUMqQ8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEbUMqQ8\App_KernelDevDebugContainer([
    'container.build_hash' => 'EbUMqQ8',
    'container.build_id' => 'ee1ecff7',
    'container.build_time' => 1688309310,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEbUMqQ8');
