<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQZATshE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQZATshE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQZATshE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQZATshE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQZATshE\App_KernelDevDebugContainer([
    'container.build_hash' => 'QZATshE',
    'container.build_id' => '6d191130',
    'container.build_time' => 1688411460,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQZATshE');
