<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQFvS1OM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQFvS1OM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQFvS1OM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQFvS1OM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQFvS1OM\App_KernelDevDebugContainer([
    'container.build_hash' => 'QFvS1OM',
    'container.build_id' => '13ff0110',
    'container.build_time' => 1688421919,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQFvS1OM');
